# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9.0@sha256:43b30884495179c4514313d0866b1ba86c5338b6bdd60ebde1ad1cb7af4b03ba
      - image: redis:3.2.12
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "Pipfile.lock" }}
            - cache-
      - run:
          name: Install dependencies
          command: |
            pip install --user pipenv
            pipenv sync --dev
      - save_cache:
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache
      - run:
          name: run tests
          command: |
            set -eu
            pipenv run flake8 .
            pipenv run mypy .
            pipenv run isort -rc --check-only
            pipenv run python setup.py test
