# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.0b1@sha256:c07616a2d42c60b559b911bafa3da40d97d5ddc074c43f8680c82d9a824e05ea
      - image: redis:3.2.12
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "Pipfile.lock" }}
            - cache-
      - run:
          name: Install dependencies
          command: |
            pip install --user pipenv
            pipenv sync --dev
      - save_cache:
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache
      - run:
          name: run tests
          command: |
            set -eu
            pipenv run flake8 .
            pipenv run mypy .
            pipenv run isort -rc --check-only
            pipenv run python setup.py test
